version: "3"

services:
    mysql:
        image: mysql:8.0.26
        container_name: mysql
        environment:
            MYSQL_DATABASE: "music_app"
            MYSQL_ROOT_PASSWORD: "rootpw"
        networks:
            - music_app
        ports:
            - "3306:3306"
        deploy:
            restart_policy:
                condition: on-failure

    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        networks:
            - music_app
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: rootpw
        deploy:
            restart_policy:
                condition: on-failure

    node_server:
        container_name: node_server
        build:
            dockerfile: Docker/node_server/Dockerfile
            context: ./
        command: npm start
        networks:
            - music_app
        volumes:
            - ./node_server:/node_server
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        deploy:
            restart_policy:
                condition: on-failure

networks:
    music_app:
        external: true