version: "3"

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "music_app"
      MYSQL_ROOT_PASSWORD: "rootpw"
    networks:
      - music_app
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin
    networks:
      - music_app
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpw
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  node_server:
    container_name: node_server
    build:
      dockerfile: Docker/node_server/Dockerfile
      context: ./
    command: npm run dev
    networks:
      - music_app
    volumes:
      - ./node_server:/node_server
      - /node_server/node_modules
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

networks:
  music_app:
    external: true